### ISSUE TITLE
`self.manifest_force` defaults to `True`.

### ISSUE THREAD

**Issue by thruflo** [tav/assetgen#10]
Having updated to version `0.3`, I found my AssetGenRunner instance was outputting a new manifest every second, because the `self.manifest_force` was True, despite not setting `output.manifest.force` or using the `--force` flag.

For reference, my relevant yaml config was:

```
output.directory: ../var/assets
output.hashed: true
output.manifest: ../var/assets/assets.json
profile.dev:
  output.hashed: false
  css.compress: false
  js.compress: false
```

My command was:

```
assetgen:   assetgen --profile dev --watch
```

Adding this line to the config solved the issue:

```
output.manifest.force: false
```

But this should presumably default to false, as the `--force` flag is set to store true only if provided.  Logging the following above line 680 in AssetGenRunner.**init**:

```
log.info((config.pop('output.manifest.force', False), force))
```

Gave me `(True, None)` so presumably its an issue with the config.
